2018-12-10 12:12:02,443 ERROR: Exception on /new_porch [GET] [in /Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/app/routes.py", line 188, in addPorch
    porchfests = Porchfest.objects()
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/mongoengine/queryset/manager.py", line 37, in __get__
    queryset = queryset_class(owner, owner._get_collection())
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/mongoengine/document.py", line 201, in _get_collection
    db.client.is_primary:
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/pymongo/mongo_client.py", line 857, in is_primary
    return self._server_property('is_writable')
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/pymongo/mongo_client.py", line 689, in _server_property
    writable_server_selector)
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/pymongo/topology.py", line 224, in select_server
    address))
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/pymongo/topology.py", line 183, in select_servers
    selector, server_timeout, address)
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/pymongo/topology.py", line 199, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 61] Connection refused
2018-12-10 12:12:16,562 ERROR: Exception on /new_porch [GET] [in /Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/app/routes.py", line 189, in addPorch
    form.porchfest_id.choices = [(p.location.zip_code, p.location.city+", "+p.location.state+" "+p.start_time.strftime("%m-%d-%Y %H:%M")+" to "+p.end_time.strftime("%m-%d-%Y %H:%M")) for p in porchfests]
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/app/routes.py", line 189, in <listcomp>
    form.porchfest_id.choices = [(p.location.zip_code, p.location.city+", "+p.location.state+" "+p.start_time.strftime("%m-%d-%Y %H:%M")+" to "+p.end_time.strftime("%m-%d-%Y %H:%M")) for p in porchfests]
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/mongoengine/queryset/queryset.py", line 99, in _iter_results
    self._populate_cache()
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/mongoengine/queryset/queryset.py", line 118, in _populate_cache
    self._result_cache.append(six.next(self))
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/mongoengine/queryset/base.py", line 1484, in __next__
    raw_doc = six.next(self._cursor)
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/pymongo/cursor.py", line 1189, in next
    if len(self.__data) or self._refresh():
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/pymongo/cursor.py", line 1087, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1563, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1516, in __start_session
    server_session = self._get_server_session()
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1549, in _get_server_session
    return self._topology.get_server_session()
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/pymongo/topology.py", line 427, in get_server_session
    None)
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/pymongo/topology.py", line 199, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 61] Connection refused
2018-12-10 12:12:18,075 ERROR: Exception on /new_porch [GET] [in /Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/app/routes.py", line 189, in addPorch
    form.porchfest_id.choices = [(p.location.zip_code, p.location.city+", "+p.location.state+" "+p.start_time.strftime("%m-%d-%Y %H:%M")+" to "+p.end_time.strftime("%m-%d-%Y %H:%M")) for p in porchfests]
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/app/routes.py", line 189, in <listcomp>
    form.porchfest_id.choices = [(p.location.zip_code, p.location.city+", "+p.location.state+" "+p.start_time.strftime("%m-%d-%Y %H:%M")+" to "+p.end_time.strftime("%m-%d-%Y %H:%M")) for p in porchfests]
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/mongoengine/queryset/queryset.py", line 99, in _iter_results
    self._populate_cache()
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/mongoengine/queryset/queryset.py", line 118, in _populate_cache
    self._result_cache.append(six.next(self))
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/mongoengine/queryset/base.py", line 1484, in __next__
    raw_doc = six.next(self._cursor)
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/pymongo/cursor.py", line 1189, in next
    if len(self.__data) or self._refresh():
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/pymongo/cursor.py", line 1087, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1563, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1516, in __start_session
    server_session = self._get_server_session()
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1549, in _get_server_session
    return self._topology.get_server_session()
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/pymongo/topology.py", line 427, in get_server_session
    None)
  File "/Users/grodriguez/Desktop/CS205/porchfest_BAG/venv/lib/python3.7/site-packages/pymongo/topology.py", line 199, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 61] Connection refused
